_target_: src.models.dcgan.model.DCGAN

z_dim: 100
lr: 0.0002
device: 'cuda'

gen:
  _target_: src.models.dcgan.generator.Generator
  z_dim: ${model.z_dim}
  im_chan: 1
  hidden_dim: 64

disc:
  _target_: src.models.dcgan.discriminator.Discriminator
  im_chan: 1
  hidden_dim: 64
