_target_: src.models.gan.model.GAN

# optimizer:
  # _target_: torch.optim.Adam
  # _partial  _: true


gen:
  _target_: src.models.gan.generator.Generator
  z_dim: ${model.z_dim}
  im_dim: 784
  hidden_dim: 128

disc:
  _target_: src.models.gan.discriminator.Discriminator
  im_dim: 784
  hidden_dim: 128

z_dim: 64
lr: 0.00001
device: 'cuda'