# @package _global_

# specify here default configuration
# order of defaults determines the order in which configs override each other
defaults:
  - datamodule: gan_mnist.yaml #TODO: change this
  - model: gan.yaml
  - callbacks: gan.yaml
  - logger: wandb # set logger here or use command line (e.g. `python train.py logger=tensorboard`)
  - trainer: default.yaml
  - paths: default.yaml
  - hydra: default.yaml
  - _self_

# task name, determines output directory path
task_name: "train"

# tags to help you identify your experiments
tags: ["dev"]

# set False to skip model training
train: True

# simply provide checkpoint path to resume training
ckpt_path: null

# seed for random number generators in pytorch, numpy and python.random
seed: null

model:
  gen:
    im_chan: ${datamodule.img_dims}
  disc:
    im_chan: ${datamodule.img_dims}

callbacks:
  wandb_callback:
    z_dim: ${model.z_dim}
    im_chan: ${datamodule.img_dims}
    img_size: ${datamodule.img_size}
