_target_: src.datamodules.gan_mnist_datamodule.GANMNISTDataModule
data_dir: ${paths.data_dir}
batch_size: 128
num_workers: 12

transform:
  _target_: torchvision.transforms.Compose
  transforms:
    - _target_: torchvision.transforms.ToTensor
    - _target_: torchvision.transforms.Resize
      size: 64
    - _target_: torchvision.transforms.Normalize
      mean: [0.5,]
      std: [0.5,]